package template

import (
	"fmt"
	"github.com/cbroglie/mustache"
)

const templateString = `
	// Code generated by {{CMD}}; DO NOT EDIT.
	package {{Package}}
	
	import (
		"github.com/tatskaari/gendb/builder"
	)
	const TableName = "{{TableName}}"
	var (
		{{#Columns}}
		{{VariableName}} = builder.Col("{{ColName}}")
		{{/Columns}}
		{{type}}AllColumns = []string{
			{{#Columns}}
			"{{ColName}}",
			{{/Columns}}
		}
	)
`

type Data struct {
	Package string
	CMD string
	TableName string
	Columns   []Column
}

type Column struct {
	VariableName string
	ColName      string
}

func Generate(data Data) (string, error) {
	template, err := mustache.ParseString(templateString)
	if err != nil {
		return "", fmt.Errorf("failed to parse table mustache template: %w", err)
	}

	res, err := template.Render(data)
	if err != nil {
		return "", fmt.Errorf("failed to redner table mustache template, data: %v: %w", data, err)
	}
	return res, nil
}

