// Code generated by recgen --file=model.go --record_struct=UserVersion --table_name=&#34;user_versions&#34;; DO NOT EDIT.
package model

import (
	"github.com/tatskaari/gendb/builder"
)

const TableName = "user_versions"

var (
	UserVersionID              = builder.Col("user_versions.id")
	UserVersionUserID          = builder.Col("user_versions.user_id")
	UserVersionActive          = builder.Col("user_versions.active")
	UserVersionFirstName       = builder.Col("user_versions.first_name")
	UserVersionLastName        = builder.Col("user_versions.last_name")
	UserVersionCreateTimestamp = builder.Col("user_versions.created_timestamp")
	AllColumns                 = []string{
		"user_versions.id",
		"user_versions.user_id",
		"user_versions.active",
		"user_versions.first_name",
		"user_versions.last_name",
		"user_versions.created_timestamp",
	}
)
