// Code generated by recgen --file=model.go --record_struct=User --table_name=&#34;users&#34;; DO NOT EDIT.
package model

import (
	"github.com/tatskaari/gendb/builder"
)

const TableName = "users"

var (
	UserID          = builder.Col("users.id")
	UserCreatedTime = builder.Col("users.created_timestamp")
	AllColumns      = []string{
		"users.id",
		"users.created_timestamp",
	}
)
